global:
scrape_configs:
  - job_name: 'springboot-essentials-actuator'
      # vai buscar as métricas na minha aplicação a cada 5 segundos
    scrape_interval: 5s
      # Onde ele vai buscar as métricas
    metrics_path: "/actuator/prometheus"
      # Endereço de onde irá acessar /actuator/prometheus. Se o Prometheus estivesse instalado em minha maquina,
      # seria no localhost:8080, ja que ele estaria na mesma maquina da aplicação. Como ele está no docker (Numa maquina virtual dentro da minha)
      #  tenho que informar que é no localhost da maquina fisica onde o docker está
    static_configs:
        #Como minha aplicação está rodando na porta 8080, eu informo que ele estará
        # coletando as infos na porta interna do host do docker (maquina onde o docker está rodando) na porta 8080
      - targets: [ 'host.docker.internal:8080' ]
